export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const TOGGLE_TO_WISHLIST = "TOGGLE_TO_WISHLIST"
export const DECREASE_QUANTITY = "DECREASE_QUANTITY"
